# Generated by Django 4.1.7 on 2023-03-13 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="form",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="form",
            name="id",
        ),
        migrations.AddField(
            model_name="form",
            name="form_JSON",
            field=models.TextField(default="empty"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="form",
            name="form_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="form",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="form",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="form",
            name="user_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="form",
            name="description",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="form",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name="form",
            table="forms",
        ),
    ]
