# Generated by Django 4.1.7 on 2023-03-13 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="form",
            name="created",
            field=models.DateTimeField(),
        ),
    ]
