# Generated by Django 4.1.7 on 2023-03-13 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_rename_created_form_created_at_remove_form_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="response",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="response",
            old_name="form",
            new_name="form_id",
        ),
        migrations.RemoveField(
            model_name="response",
            name="id",
        ),
        migrations.RemoveField(
            model_name="response",
            name="response_text",
        ),
        migrations.AddField(
            model_name="response",
            name="response_JSON",
            field=models.TextField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="response",
            name="response_id",
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="response",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="response",
            name="user_id",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterModelTable(
            name="response",
            table="responses",
        ),
    ]
