# Generated by Django 4.1.7 on 2023-03-13 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_form_created"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forms",
            fields=[
                ("form_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.IntegerField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.IntegerField(blank=True, null=True)),
                (
                    "form_json",
                    models.TextField(blank=True, db_column="form_JSON", null=True),
                ),
            ],
            options={
                "db_table": "forms",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="ProjectsForm",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "db_table": "projects_form",
                "managed": False,
            },
        ),
    ]
