# Generated by Django 4.1.7 on 2023-03-20 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_forms_projectsform"),
        ("projects", "0006_rename_created_response_created_at_and_more"),
    ]

    operations = []
